// Generated by gencpp from file spinn_ros_msgs/pop_list.msg
// DO NOT EDIT!


#ifndef SPINN_ROS_MSGS_MESSAGE_POP_LIST_H
#define SPINN_ROS_MSGS_MESSAGE_POP_LIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spinn_ros_msgs
{
template <class ContainerAllocator>
struct pop_list_
{
  typedef pop_list_<ContainerAllocator> Type;

  pop_list_()
    : motors()
    , setPoints()  {
    }
  pop_list_(const ContainerAllocator& _alloc)
    : motors(_alloc)
    , setPoints(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _motors_type;
  _motors_type motors;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _setPoints_type;
  _setPoints_type setPoints;




  typedef boost::shared_ptr< ::spinn_ros_msgs::pop_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spinn_ros_msgs::pop_list_<ContainerAllocator> const> ConstPtr;

}; // struct pop_list_

typedef ::spinn_ros_msgs::pop_list_<std::allocator<void> > pop_list;

typedef boost::shared_ptr< ::spinn_ros_msgs::pop_list > pop_listPtr;
typedef boost::shared_ptr< ::spinn_ros_msgs::pop_list const> pop_listConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spinn_ros_msgs::pop_list_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spinn_ros_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'spinn_ros_msgs': ['/home/roboy/workspace/spinnaker_lsm/src/spinn_ros_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spinn_ros_msgs::pop_list_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spinn_ros_msgs::pop_list_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spinn_ros_msgs::pop_list_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7da1664b5fc700acbf0efa5165c4eb21";
  }

  static const char* value(const ::spinn_ros_msgs::pop_list_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7da1664b5fc700acULL;
  static const uint64_t static_value2 = 0xbf0efa5165c4eb21ULL;
};

template<class ContainerAllocator>
struct DataType< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spinn_ros_msgs/pop_list";
  }

  static const char* value(const ::spinn_ros_msgs::pop_list_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] motors\n\
int32[] setPoints\n\
";
  }

  static const char* value(const ::spinn_ros_msgs::pop_list_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motors);
      stream.next(m.setPoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pop_list_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spinn_ros_msgs::pop_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spinn_ros_msgs::pop_list_<ContainerAllocator>& v)
  {
    s << indent << "motors[]" << std::endl;
    for (size_t i = 0; i < v.motors.size(); ++i)
    {
      s << indent << "  motors[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.motors[i]);
    }
    s << indent << "setPoints[]" << std::endl;
    for (size_t i = 0; i < v.setPoints.size(); ++i)
    {
      s << indent << "  setPoints[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.setPoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPINN_ROS_MSGS_MESSAGE_POP_LIST_H
